#!/usr/bin/env python3
"""Generate add8-netlist.mjs from add8-weapon-pack.json.

The weapon pack is the single source of truth for the ADD8 evidence (netlist bytes,
sha256, I/O layout, real mint/tapeout calldata). The generated ES module lets the
policy engine, the CLI and the browser inspector share the exact taped netlist
without a bundler, JSON import attributes, or a network round-trip.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
PACK = HERE / "add8-weapon-pack.json"
OUT = HERE / "add8-netlist.mjs"


def main() -> None:
    pack = json.loads(PACK.read_text())
    circuit = pack["circuit"]
    raw = bytes.fromhex(circuit["netlist_hex"][2:])
    sha = hashlib.sha256(raw).hexdigest()
    if sha != circuit["netlist_sha256"]:
        raise SystemExit(f"netlist sha256 mismatch: pack={circuit['netlist_sha256']} computed={sha}")
    if len(raw) != circuit["netlist_bytes"] or len(raw) % 7 != 0:
        raise SystemExit(f"unexpected netlist length {len(raw)}")

    mint = pack["calldata"]["mint_nand"]
    tape = pack["calldata"]["tapeout"]
    fees = pack["fees_wei"]

    body = f"""// GENERATED by gen_add8_netlist_module.py from add8-weapon-pack.json — do not edit by hand.
// Exact NAND netlist taped on X Layer as circuitId=1 of the LeoLabs Processor.

export const ADD8_CIRCUIT_ID = 1;
export const ADD8_N_IN = {circuit["nIn"]};
export const ADD8_N_OUT = {circuit["nOut"]};
export const ADD8_N_NAND = {circuit["nNand"]};
export const ADD8_INPUT_LABELS = Object.freeze({json.dumps(circuit["labels"]["in"])});
export const ADD8_OUTPUT_LABELS = Object.freeze({json.dumps(circuit["labels"]["out"])});
export const ADD8_OUTPUT_SIGNALS = Object.freeze({json.dumps(circuit["outputs_signal_ids"])});
export const ADD8_NETLIST_BYTES = {len(raw)};
export const ADD8_NETLIST_SHA256 = "{sha}";
export const ADD8_NETLIST_HEX =
  "{circuit["netlist_hex"]}";

// Real X Layer calldata that was broadcast for this circuit (mint 122 NAND, then tapeout).
export const ADD8_REAL_CALLS = Object.freeze({{
  mintNand: Object.freeze({{
    to: "{mint["to"]}",
    valueWei: "{mint["value_wei"]}",
    data: "{mint["data"]}",
  }}),
  tapeout: Object.freeze({{
    to: "{tape["to"]}",
    valueWei: "{tape["value_wei"]}",
    data: "{tape["data"]}",
  }}),
}});

export const ADD8_FEES_WEI = Object.freeze({{
  mintPrice: "{fees["mintPrice"]}",
  protocolFee: "{fees["protocolFee"]}",
  tapeoutFee: "{fees["TAPEOUT_FEE"]}",
}});
"""
    OUT.write_text(body)
    print(json.dumps({"wrote": str(OUT), "bytes": len(raw), "sha256": sha, "nNand": circuit["nNand"]}))


if __name__ == "__main__":
    main()
